DROP DATABASE IF EXISTS EQUIPO;

CREATE DATABASE EQUIPO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE EQUIPO;

CREATE TABLE equipo (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR (20) COLLATE utf8mb4_unicode_ci NOT NULL,
FECHA DATE NOT NULL,
DT VARCHAR (20) COLLATE utf8mb4_unicode_ci NOT NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE partidos (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) COLLATE utf8mb4_unicode_ci NOT NULL,
RIVAL VARCHAR(20) COLLATE utf8mb4_unicode_ci NOT NULL,
HORARIO DATETIME NOT NULL,
FECHA DATE NOT NULL,
LUGAR VARCHAR(20) COLLATE utf8mb4_unicode_ci NOT NULL,
RESULTADO VARCHAR (20) COLLATE utf8mb4_unicode_ci NOT NULL,
ID_equipo INT NOT NULL,
FOREIGN KEY (ID_equipo) REFERENCES equipo (ID)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE torneos (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) COLLATE utf8mb4_unicode_ci NOT NULL,
EQUIPOS INT NOT NULL,
UBICACIÓN VARCHAR(20) COLLATE utf8mb4_unicode_ci NOT NULL,
FECHA DATE NOT NULL,
ORGANIZADOR VARCHAR(20) COLLATE utf8mb4_unicode_ci NOT NULL,
ID_torneos INT NOT NULL,
FOREIGN KEY (ID_torneos) REFERENCES torneos (ID)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE plantilla (
ID INT PRIMARY KEY AUTO_INCREMENT,
TITULARES INT NOT NULL,
SUPLENTES INT NOT NULL,
ID_equipo INT NOT NULL,
FOREIGN KEY (ID_equipo) REFERENCES equipo (ID)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE dt (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) COLLATE utf8mb4_unicode_ci NOT NULL,
TELEFONO INT NOT NULL,
EMAIL VARCHAR(20) COLLATE utf8mb4_unicode_ci NOT NULL,
DIRECCIÓN VARCHAR (20) COLLATE utf8mb4_unicode_ci NOT NULL,
ID_equipo INT NOT NULL,
FOREIGN KEY (ID_equipo) REFERENCES equipo (ID) 
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE asistentedt (
ID int primary key auto_increment,
NOMBRE VARCHAR(20) COLLATE utf8mb4_unicode_ci NOT NULL,
TELEFONO INT NOT NULL,
EMAIL VARCHAR (30) COLLATE utf8mb4_unicode_ci NOT NULL,
DIRECCIÓN VARCHAR(20) COLLATE utf8mb4_unicode_ci NOT NULL,
ID_dt INT NOT NULL,
FOREIGN KEY (ID_dt) REFERENCES dt (ID) 
)CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE Registro (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) COLLATE utf8mb4_unicode_ci NOT NULL,
EMAIL VARCHAR(20) COLLATE utf8mb4_unicode_ci NOT NULL,
CONTRASEÑA VARCHAR(12) COLLATE utf8mb4_unicode_ci NOT NULL,
CCONTRASEÑA VARCHAR(12) COLLATE utf8mb4_unicode_ci NOT NULL,
CARGO VARCHAR (20) COLLATE utf8mb4_unicode_ci NOT NULL,
ID_dt INT NOT NULL,
ID_asistentedt INT NOT NULL,
FOREIGN KEY (ID_dt) REFERENCES dt (ID),
FOREIGN KEY (ID_asistentedt) REFERENCES asistentedt (ID) 
)
